version: "3.8"
services:
  alm:
    container_name: alm
    env_file: ./.env
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    volumes:
      - .:/alm
    ports:
      - 8888:8888
